main: fr.volax.syliaarmor.SyliaArmorMain
name: SyliaArmor
version: 1.1
description: SyliaArmor plugin
author: Volax
website: https://github.com/VolaxYT
commands:
  sarmor:
    description: Commande Principal